#!/usr/bin/expect -f


# Read in the IP address, username, and password from the file
set file "/home/mpotts32/control_comp/pass_ctcpu.txt"
set fh [open $file r]
gets $fh ip
gets $fh user
gets $fh password
close $fh


# Connect to the remote computer using SSH
spawn ssh $user@$ip

# Wait for the password prompt and send the password
expect "password:"
send "$password\r"

# Execute a command on the remote computer
expect "trinity@trinityCPU:~$#"
send "sudo reboot \r"


# Wait for the SSH session to close
expect eof





